# -*- coding: utf-8 -*-
"""MediQuery_Medical_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZEPQcodWhjGVc_fX426MwF4Em9E6sxI

#**MediQuery: A Medical Question-Answering Chatbot**
#1. Introduction

Healthcare information is often difficult to access in a timely and reliable manner, especially for preliminary understanding of medical conditions. With the growing adoption of artificial intelligence in healthcare, conversational agents such as chatbots can play an important role in providing general medical information and health awareness.

MediQuery is a medical question-answering chatbot designed to respond to user queries by retrieving relevant answers from a trusted medical question–answer dataset. The chatbot is implemented using Python and Natural Language Processing (NLP) techniques, specifically TF-IDF vectorization and cosine similarity, to identify the most relevant response.

This system is intended strictly for educational and informational purposes and does not provide diagnosis or treatment recommendations.

#2. Medical Disclaimer

Disclaimer

This chatbot provides general medical information only.
It is not a substitute for professional medical advice, diagnosis, or treatment.
Users experiencing serious or persistent symptoms are advised to consult a qualified healthcare professional or seek emergency medical care.

#3. Dataset Description

The chatbot uses a medical question–answer dataset consisting of pairs of commonly asked medical questions and their corresponding informational answers.

Dataset Characteristics:

Format: CSV (Comma-Separated Values)

Columns:

question – Medical-related user questions

answer – Informational responses

Nature of data:

Publicly available

Non-clinical

No personal or patient-identifiable information

The dataset is loaded into the system and used as a knowledge base for retrieving appropriate responses.

#4. Text Preprocessing

To ensure accurate comparison between user input and stored questions, the text data undergoes preprocessing.

Preprocessing Steps:

Conversion of text to lowercase

Removal of punctuation

Normalization of input for consistency

Purpose:

Preprocessing improves matching accuracy by reducing noise and ensuring uniform representation of text across the dataset and user queries.

#5. Question-Answering Methodology

The chatbot employs a retrieval-based approach rather than a generative model.

Techniques Used:

TF-IDF (Term Frequency–Inverse Document Frequency)
Converts textual questions into numerical vectors that reflect word importance.

Cosine Similarity
Measures the similarity between the user query vector and stored question vectors.

Workflow:

Dataset questions are vectorized using TF-IDF.

User input is preprocessed and vectorized.

Cosine similarity is computed.

The answer corresponding to the most similar question is returned.

This approach is explainable, efficient, and suitable for medical information systems, where transparency is important.

#6. Safety Layer

To ensure ethical and safe usage, a safety mechanism is incorporated.

Safety Features:

Detection of emergency-related keywords (e.g., chest pain, difficulty breathing)

Automatic redirection advising users to seek immediate medical attention

This layer ensures the chatbot does not attempt to respond to potentially life-threatening situations.

#7. Chatbot Execution

The chatbot runs in an interactive loop, allowing users to:

Enter medical-related questions

Receive relevant informational responses

Exit the system by typing bye

The interaction is entirely text-based and suitable for execution in Google Colab, local systems, or cloud environments.

#8. Results and Observations

The chatbot successfully retrieves relevant answers for common medical questions.

TF-IDF-based similarity provides accurate matching for well-phrased queries.

The safety layer appropriately handles emergency-related inputs.

Overall, the system demonstrates effective performance for basic medical question answering.

#9. Conclusion

Phase 1 focused on:

Structuring the project clearly

Implementing safe and ethical chatbot behavior

Ensuring the notebook is readable, organized, and evaluation-ready

At the completion of this phase, MediQuery is a functional, well-documented medical chatbot suitable for academic demonstration and further enhancement.

#Install Required Libraries
"""

!pip install pandas scikit-learn nltk

"""#Upload the Dataset"""

from google.colab import files

uploaded = files.upload()

"""Verify File Location"""

import os

os.listdir("/content")

"""#Load and Preview Dataset"""

import pandas as pd

data = pd.read_csv("/content/medical_qa.csv")
data.head()

"""#Text Preprocessing"""

import string

def clean_text(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text

"""#Build the Question-Answering Engine"""

data.columns

# Normalize column names
data.columns = data.columns.str.strip().str.lower()

data.columns

import string

def clean_text(text):
    text = str(text).lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text

# Create cleaned question column
data["clean_question"] = data["question"].apply(clean_text)

data.head()

"""#Add Medical Safety Layer"""

EMERGENCY_KEYWORDS = [
    "chest pain", "difficulty breathing",
    "severe bleeding", "unconscious"
]

def safety_check(text):
    for word in EMERGENCY_KEYWORDS:
        if word in text:
            return True
    return False

"""#Run the Chatbot Loop

Define get_answer()
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Create vectorizer and vectors (ensure this cell runs)
vectorizer = TfidfVectorizer()
question_vectors = vectorizer.fit_transform(data["clean_question"])

def get_answer(user_input):
    user_vector = vectorizer.transform([user_input])
    similarity = cosine_similarity(user_vector, question_vectors)
    index = similarity.argmax()
    return data["answer"].iloc[index]

"""Define safety_check()"""

EMERGENCY_KEYWORDS = [
    "chest pain", "difficulty breathing",
    "severe bleeding", "unconscious"
]

def safety_check(text):
    for keyword in EMERGENCY_KEYWORDS:
        if keyword in text:
            return True
    return False

"""Ensure clean_text"""

import string

def clean_text(text):
    text = str(text).lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    return text

"""Run the Chatbot Loop"""

print("MediQuery: Medical Question-Answering Chatbot")
print("Disclaimer: This chatbot provides general medical information only.\n")

while True:
    user_input = input("User: ")

    if user_input.lower() == "bye":
        print("Bot: Take care. Stay healthy!")
        break

    cleaned_input = clean_text(user_input)

    if safety_check(cleaned_input):
        print("Bot: Please seek immediate medical attention or contact emergency services.")
    else:
        response = get_answer(cleaned_input)
        print("Bot:", response)

"""#Test with Example Questions"""

What is fever?
What causes headache?
I have chest pain
bye